[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  PRISMA_CLI_BINARY_TARGETS = "native,debian-openssl-1.1.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", ".prisma/client"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false
  conditions = {path = ["/api/*"]}
